global:
  resolve_timeout: "5m"
receivers:
- name: "null"
- name: slack_general
  slack_configs:
    - api_url: <slack_webhook>
route:
  group_by:
  - "job"
  group_interval: "5m"
  group_wait: "30s"
  receiver: "null"
  repeat_interval: "12h"
  routes:
  - match:
      severity: slack
    receiver: slack_general
  - match:
      alertname: "Watchdog"
    receiver: "null"
