apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: node-disk-space
  namespace: openshift-monitoring
spec:
  groups:
  - name: node-low-root-disk
    rules:
    - alert: NodeRootDiskLow
      annotations:
        message: machine {{ $labels.instance }} has less than 30% free space on root fs
      expr: |
        (node_filesystem_free_bytes{mountpoint="/"}/node_filesystem_size_bytes{mountpoint="/"}*100) < 30
      for: 5m
      labels:
        severity: slack
  - name: node-critical-root-disk
    rules:
    - alert: NodeRootDiskCritical
      annotations:
        message: 'machine {{ $labels.instance }} has less than 15% free space on root fs for 30 minutes
          use oc describe node {{ $labels.instance }} to investigate'
      expr: |
        (node_filesystem_free_bytes{mountpoint="/"}/node_filesystem_size_bytes{mountpoint="/"}*100) < 15
      for: 30m
      labels:
        severity: slack
